### ISSUE TITLE
Refactor PostMaker mention button

### ISSUE THREAD

**Issue by 7alip** [freedomcombination/monorepo#1120]
- Simplify adding mention process.
- Add a random mention when the buttons are clicked
- Remove modals/drawers

**Tasks**

- [x] Remove and `MentionList` components and their modals from PostMaker component
- [x] Do not delete the component files as we may use them in the future.
- [x] Keep setting `activePostId` action when the buttons are clicked
- [x] Clicking on the `Mention` button will trigger `addMentionToPost` with a random username from `savedMentions` list 
   _(Use `shuffle` method from lodash)_

**Comment by bbluechip** [comment]
Can I get a detailed information about this issue.

**Comment by 7alip** [comment]
@bbluechip I updated the description. If you would still like to take on this task, feel free to assign yourself.

**Comment by 7alip** [comment]
@bbluechip I updated the description. You will adjust only the mention button, we will keep the trends components as they are
