### ISSUE TITLE
Display an active hashtag modal when users first visit the TrendRights website during the hashtag event.

### ISSUE THREAD

**Issue by 7alip** [freedomcombination/monorepo#1155]
## Description

Enhance website functionality to automatically redirect users to the PostMaker page during active hashtag events. Implement this feature universally across all pages using Next.js middleware, leveraging Vercel's `Edge Config` and cookies for efficient execution.

> I created a edge config called `last-hashtag` from Vercel dashboard. 
Config Id: `ecfg_teewtrjl8mpox0ulyt68bd43hgbi`. 
Some new env variables needs to be added to env.local 

## Tasks

- [ ] **[Update](https://vercel.com/docs/storage/edge-config/vercel-api#update-your-edge-config-items)** `last-hashtag` edge config key whenever an hashtag is created.
  _This can be managed through Strapi's lifecycle hooks (afterCreate, afterUpdate)_
  _The config value should contain the hashtag's slug and hashtag's date in ISO format (e.g., `patient-rights__2024-04-07T10:19:00.000Z`)._
- [ ] Use two cookies
  1. `pm-ir` (boolean) (_post maker is redirected_)
  2. `pm-lhs` (_post maker lasthashtag slug)_)
  _Set this `pm-ir` cookie to true when user closes the modal or clicks on the PM redirect link and update `pm-lhs` cookie with the edge config slug_
- [ ] In Next.js middleware, check if the current ISO time is within the latest active hashtag event and compare cookie-config slugs. 
  _Hashtag datetime + 12 hours_
- [ ] Trigger the hashtag modal conditionally based on `pm-ir` cookie in the layout 

## Example

```ts
import { NextResponse } from 'next/server';
import { get } from '@vercel/edge-config';

export async function middleware() {
  const lastHashtag = await get('last-hashtag');
  
  const [slug, dateStr] = (lastHashtag || '').split('__');
  // ...
}
```
