### ISSUE TITLE
`FormUploader` section for markdown editor in Create/Edit forms

### ISSUE THREAD

**Issue by 7alip** [freedomcombination/monorepo#1171]
### Description

Currently, users are required to upload images to Strapi or provide external image URLs to use images in the markdown editor. To simplify this process, we can implement direct image uploads from the Model(Create/Edit)Form components. This will enable users to generate image URLs within the form.

### Tasks

- [ ] Create a `FormUploader` component. It can have `onUpload` event handler which returns the generated image URLS.
- [ ] Render this component just above the markdown editor only if the form fields contain `markdown` type
- [ ] Display all sized of the generated URLs in a select component
- [ ] Clear button will reset the state and show the upload button

<img width="1070" alt="FormUploader" src="https://github.com/freedomcombination/monorepo/assets/22167684/a92ab637-b747-4642-a333-16274731d445">

**Comment by 7alip** [comment]
@bbluechip Could you please pick one issue at a time

**Comment by bbluechip** [comment]
Could I take this?
