### ISSUE TITLE
Add custom 404 page

### ISSUE THREAD

**Issue by 7alip** [freedomcombination/monorepo#1193]
### Tasks

- [ ] Create `NotFound` component in `ui` package
- [ ] Add `404.tsx` page into all frontend apps
- [ ] Import NotFound into 404 pages
