### ISSUE TITLE
Asset and asset tracking improvement

### ISSUE THREAD

**Issue by MustafaTRKYLMZ** [freedomcombination/monorepo#1408]
### Is your feature request related to a problem? Please describe.

- [x] Add a relationship between the asset and the platform.
- [x] Add `location` and `platform` filter to assets page
- [ ] #1428
- [ ] #1423
- [x] Display the SKU number in the details view. Ensure that it is read-only and cannot be edited.
- [x] Add a new column to the asset table: "People In Charge".
- [x] Ensure that the SKU is the first column in the asset table.
