### ISSUE TITLE
FEAT: Add Google like PlatformsMenu

### ISSUE THREAD

**Issue by MustafaTRKYLMZ** [freedomcombination/monorepo#1458]
### Is your feature request related to a problem? Please describe.

Add a switch button to the layout, visible only if the user has a role beyond the default "authenticated" and "public" roles. This button will allow users to toggle between the websites of the platforms and the foundation.

The Google Apps 9-point icon serves as an excellent example for the design and placement of this switch button.

<img width="300" src="https://github.com/freedomcombination/monorepo/assets/58182269/8a3e69a4-5d03-4a52-9c73-c834c85dbcc1" />

### Describe the solution you'd like

**Tasks**

- [ ] Create `PlatformsMenu` component with [popover](https://v2.chakra-ui.com/docs/components/popover)
- [ ] Place `PlatformsMenu` popover next to Signin/Profile button.
  - It should be visible for both mobile and desktop
- [ ] Use `import { PiDotsNineBold } from "react-icons/pi"` icon for PopoverTrigger IconButton
- [ ] `PlatformsMenu` will bi visible only for `foundation` site.
  - You can use `site` from auth context `const { site } = useAuthContext()`
- [ ] Each app has logo in its own apps/<app>/public folder. Duplicate these logos into `apps/foundation/public`
  - Use these logos in PopoverContent grid. `<SimpleGrid columns={2}>`
  - Apps:
    - dashboard => foundation-logo => https://dashboard.freedomcombination.com
    - kunsthalte => kunsthalte-logo => https://kunsthalte.com
    - lotus => lotus-logo => https://lotusvdmedia.com (not available yet)
    - trend-rights => trend-rights.logo => https://trendrights.com
