### ISSUE TITLE
FEAT: Add unsubscribe push notifications

### ISSUE THREAD

**Issue by 7alip** [freedomcombination/monorepo#1812]
### Todos

- [x] Add a button to unsubscribe from push notifications
- [x] Remove Subscriber data from the database
- [ ] Unregister service worker
- [ ] Remove the __PN-SUBSCRIBED cookie
