### ISSUE TITLE
Add `Other Jobs` (non platform related ones) to Join Form

### ISSUE THREAD

**Issue by MustafaTRKYLMZ** [freedomcombination/monorepo#952]
### Description

<img width="579" alt="Screenshot 2024-04-28 at 23 00 13" src="https://github.com/freedomcombination/monorepo/assets/22167684/d25b9385-09be-4a3c-8872-3b2d08185d7d">

In JoinForm, we display jobs for each platform. However, some jobs may be unrelated to any platform, indicating that they are directly related to the foundation.

### Tasks

- [x] Fetch `foundationJobs` (use platform filter null) in `JoinTemplate.tsx`.
- [x] Pass `foundationJobs` to JoinForm
- [x] Add `Freedom Combination Foundation` section to top of Jobs section in the form, list the `foundationJobs`
